# Generated by Django 6.0.1 on 2026-02-01 08:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2 or alpha-3 country code', max_length=3, unique=True)),
                ('country_name', models.CharField(help_text='Full country name', max_length=100)),
                ('vat_rate', models.DecimalField(decimal_places=2, help_text='VAT/IVA rate as percentage (e.g., 19.00 for 19%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('customs_duty_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Average customs duty rate as percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('de_minimis_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Value below which no import taxes apply (in USD)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency_code', models.CharField(default='USD', help_text='Local currency code (ISO 4217)', max_length=3)),
                ('notes', models.TextField(blank=True, default='', help_text='Additional notes about import regulations')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tax rate is currently active')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Import Tax Rate',
                'verbose_name_plural': 'Import Tax Rates',
                'db_table': 'import_tax_rates',
                'ordering': ['country_name'],
            },
        ),
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Unique marketplace code (e.g., 'EBAY_US', 'MLC')", max_length=20, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'eBay USA', 'MercadoLibre Chile')", max_length=100)),
                ('provider', models.CharField(choices=[('ebay', 'eBay'), ('mercadolibre', 'MercadoLibre')], help_text='Marketplace provider', max_length=20)),
                ('country_code', models.CharField(help_text='ISO country code', max_length=3)),
                ('country_name', models.CharField(help_text='Country name for display', max_length=100)),
                ('api_site_id', models.CharField(blank=True, default='', help_text="API site identifier (e.g., 'MLC' for MercadoLibre Chile)", max_length=20)),
                ('currency_code', models.CharField(default='USD', help_text='Default currency code', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this marketplace is currently supported')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display in UI (lower = first)')),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
                'db_table': 'marketplaces',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
