# Generated by Django 5.1.15 on 2026-02-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importtaxrate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
